CREATE TABLE policy_component (
	id NUMBER(19,0) NOT NULL,
	tenant_id VARCHAR2(36) NOT NULL,
	policy_id NUMBER(19,0) NOT NULL,
	component_type NUMBER(10,0) NOT NULL,
	component_json CLOB NOT NULL,
	CONSTRAINT project_policy_component_pkey PRIMARY KEY(id),
	CONSTRAINT fk_policy_component_tenant FOREIGN KEY(tenant_id) REFERENCES tenant(id) ON DELETE CASCADE
);

CREATE SEQUENCE  "POLICY_COMPONENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
